# Generated by Django 4.1 on 2024-05-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForcastOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('office_id', models.CharField(db_index=True, max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=24)),
                ('fax_number', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=255)),
                ('nws_region', models.CharField(max_length=4)),
                ('parent_organization', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forcast office',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('lat', models.FloatField(default=0.0)),
                ('long', models.FloatField(default=0.0)),
                ('grid_id', models.CharField(db_index=True, max_length=8)),
                ('grid_x', models.IntegerField(default=0)),
                ('grid_y', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('generated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('update_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_office', to='web.forcastoffice')),
            ],
            options={
                'verbose_name': 'Location',
            },
        ),
        migrations.CreateModel(
            name='ForcastPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
                ('is_daytime', models.BooleanField(default=False)),
                ('temperature', models.IntegerField()),
                ('temperature_unit', models.CharField(default='F', max_length=1)),
                ('temperature_trend', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('win_speed', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('win_direction', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('icon', models.CharField(max_length=255)),
                ('short_forecast', models.CharField(max_length=255)),
                ('detailed_forecast', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forcast_period', to='web.location')),
            ],
            options={
                'verbose_name': 'Weather forcast periods',
            },
        ),
    ]
